# Generated by Django 5.2.7 on 2025-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rooms', 'Rooms'), ('car_rent', 'Car_Rent'), ('fitness', 'Fitness'), ('restaurant', 'Restaurant'), ('sauna', 'Sauna'), ('spa', 'Spa'), ('meeting_room', 'Meeting_Room')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number', models.PositiveIntegerField(max_length=3, unique=True)),
                ('name', models.CharField(choices=[('Suite', 'Suite'), ('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Romantic', 'Romantic'), ('Erotic', 'Erotic')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
