# Generated by Django 5.2.7 on 2025-10-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_out',
            field=models.DateField(),
        ),
    ]
