# Generated by Django 5.2.7 on 2025-10-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rooms', 'Rooms'), ('car_rent', 'Car_Rent'), ('fitness', 'Fitness'), ('restaurant', 'Restaurant'), ('sauna', 'Sauna'), ('spa', 'Spa'), ('meeting_room', 'Meeting_Room')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flour', models.PositiveSmallIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('max_pers', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
