# Generated by Django 5.2.7 on 2025-10-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_rent',
            name='qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='name',
            field=models.CharField(choices=[('FIAT GRANDE PANDA', 'Fiat Grande Panda'), ('LANCIA YPSILON 2024', 'Lancia Ypsilon 2024'), ('LAMBORGHINI AVENTADOR', 'Lamborghini Aventador'), ('AUDI A3', 'Audi A3'), ('MERCEDES CLE', 'Mercedes CLE'), ('PEUGEOT 3008', 'Peugeot 3008'), ('RENAULT CAPTUR', 'Renault Captur'), ('CIROEN C5', 'Citroën C5')], max_length=50),
        ),
    ]
