# Generated by Django 5.2.7 on 2025-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_alter_spabooking_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='spa',
            name='name',
            field=models.CharField(default='Spa', max_length=100),
        ),
    ]
