# Generated by Django 5.2.7 on 2025-10-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meeting_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_room.meetingroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
