# Generated by Django 5.2.7 on 2025-10-29 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meeting_room', '0002_meetingroombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroombooking',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
