# Generated by Django 5.2.7 on 2025-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0003_alter_saunabooking_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauna',
            name='name',
            field=models.CharField(default='Sauna', max_length=100),
        ),
    ]
