name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
       DJANGO_SECRET_KEY: test_secret
       DJANGO_DEBUG: False
       DATABASE_URL: postgres://postgres:postgres@localhost:5432/mercure_test
       DJANGO_CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt

      - name: Run Django migrations
        working-directory: config
        run: |
          python manage.py migrate

      - name: Run tests
        working-directory: config
        run: |
          pytest -v
